### PR TITLE
Adding seed for randomized activities

### PR DESCRIPTION
**Pull request by TWINGSISTER**
Seed can be a positive number between 0 and 99. If zero a Geogebra activity generated using randomness will be different upon every reload. If not zero, upon reload, the same randomized version is presented.  Using two different seeds will give two different randomized versions. Use a zero seed to give each student a different test. Use a non zero seed for guided test practicing to be sure that all the students receive the same test.

### CODE REVIEW

**Comment by toniginard** [comment]
Hi @TWINGSISTER,

Thanks for your Pull Request.

I have been trying your code and I couldn't get the described behavior. Can you provide test instructions to check how do randomized activities work? Do the GeoGebra activities have to meet any requirement for this functionality to work?


Many thanks,

**Comment by TWINGSISTER** [comment]
I am so sorry, this was some time ago! I will try to recollect my findings and reply to you later. It is the first time I  try to join a GitHub project, please be patent.

   ---------- Original message ----------
   From "Toni Ginard" ***@***.***
   To "projectestac/moodle-mod_geogebra" ***@***.***
   Cc "TWINGSISTER" ***@***.***,"Mention" ***@***.***
   Date Fri, 05 Nov 2021 05:21:23 -0700
   Subject Re: [projectestac/moodle-mod_geogebra] Adding seed for randomized activities (#53)

   Hi @TWINGSISTER,

   Thanks for your Pull Request.

   I have been trying your code and I couldn't get the described behavior. Can you provide test instructions to check how do randomized activities work? Do the GeoGebra activities have to meet any requirement for this functionality to work?

   Many thanks,

   —
   You are receiving this because you were mentioned.
   Reply to this email directly, view it on GitHub, or unsubscribe.
   Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by toniginard** [comment]
In commit ac1da33a60fdc4f325ae40333353c72fbc220276, I have integrated separately the Seed functionality.

Regarding the parameter to store the Geogebra javascript URL, I think the solution implemented is not correct because that parameter is common to all the activities. The correct approach should be to add a configuration section for the module and set the parameter there. I will work on it.

Best wishes.

**Comment by TWINGSISTER** [comment]
Well, this would be nice to have, too. Nevertheless please consider that this parameter could be out of reach of the teacher capabilities and this will start an argument for the ones that want to use their own GGB implemention and have to convince all the colleagues.

   ---------- Original message ----------
   From "Toni Ginard" ***@***.***
   To "projectestac/moodle-mod_geogebra" ***@***.***
   Cc "TWINGSISTER" ***@***.***,"Mention" ***@***.***
   Date Fri, 03 Dec 2021 02:31:55 -0800
   Subject Re: [projectestac/moodle-mod_geogebra] Adding seed for randomized activities (#53)

   In commit ac1da33, I have integrated separately the Seed functionality.

   Regarding the parameter to store the Geogebra javascript URL, I think the solution implemented is not correct because that parameter is common to all the activities. The correct approach should be to add a configuration section for the module and set the parameter there. I will work on it.

   Best wishes.

   —
   You are receiving this because you were mentioned.
   Reply to this email directly, view it on GitHub, or unsubscribe.
   Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by toniginard** [comment]
Well, I had not thought of that possibility. In that case, it might be possible to add a general parameter and an optional value as you have proposed. I made a branch based on your work only for that change: https://github.com/projectestac/moodle-mod_geogebra/tree/WIP-config-url


Thanks for your feedback!

**Comment by TWINGSISTER** [comment]
That's ok. PLease consider that I am maintaining a GitHub repo that takes monthly the Geogebra GitHub repo and tries to produce suitable GGB javascript code for integration in Moodle via this plugin

   https://github.com/TWINGSISTER/Geogebra-Javascript-Bundle/releases

   Please do not hesitate to contact me if this do not work.

   Regards

   ---------- Original message ----------
   From "Toni Ginard" ***@***.***
   To "projectestac/moodle-mod_geogebra" ***@***.***
   Cc "TWINGSISTER" ***@***.***,"Mention" ***@***.***
   Date Fri, 03 Dec 2021 03:27:09 -0800
   Subject Re: [projectestac/moodle-mod_geogebra] Adding seed for randomized activities (#53)

   Well, I had not thought of that possibility. In that case, it might be possible to add a general parameter and an optional value as you have proposed. I made a branch based on your work only for that change: https://github.com/projectestac/moodle-mod_geogebra/tree/WIP-config-url

   Thanks for your feedback!

   —
   You are receiving this because you were mentioned.
   Reply to this email directly, view it on GitHub, or unsubscribe.
   Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by toniginard** [comment]
Hi!

I have included the seeds functionality and released module version 3.6.4 with it. I also included the parameters to customize the deploy ggb URL and released version 3.6.5. As I mentioned, there is a module-level parameter and an activity-level parameter. Activity-level has precedence over module-level, so there is a default value for the site that can be customized in each activity.

Many thanks for your contributions!

**Pull request closed without merging**
